name: rocm310
channels:
  - conda-forge
  - conda-forge/label/broken
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.11.18
  - aiosignal=1.3.2
  - async-timeout=5.0.1
  - attrs=25.3.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.0
  - aws-c-common=0.12.2
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.4
  - aws-c-http=0.10.1
  - aws-c-io=0.19.0
  - aws-c-mqtt=0.13.0
  - aws-c-s3=0.7.17
  - aws-c-sdkutils=0.2.3
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.32.5
  - aws-sdk-cpp=1.11.510
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - blas=2.131
  - blas-devel=3.9.0
  - bottleneck=1.4.2
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.4.26
  - certifi=2025.4.26
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - colorama=0.4.6
  - coloredlogs=15.0.1
  - cpython=3.10.17
  - dataclasses=0.8
  - datasets=1.18.3
  - dill=0.4.0
  - filelock=3.18.0
  - frozenlist=1.6.0
  - fsspec=2025.3.2
  - gflags=2.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - h2=4.2.0
  - hpack=4.1.0
  - huggingface_hub=0.30.2
  - humanfriendly=10.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - jinja2=3.1.6
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.43
  - libabseil=20250127.1
  - libarrow=20.0.0
  - libarrow-acero=20.0.0
  - libarrow-dataset=20.0.0
  - libarrow-substrait=20.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.13.0
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgomp=15.1.0
  - libgoogle-cloud=2.36.0
  - libgoogle-cloud-storage=2.36.0
  - libgrpc=1.71.0
  - libiconv=1.18
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libopenblas=0.3.29
  - libopentelemetry-cpp=1.20.0
  - libopentelemetry-cpp-headers=1.20.0
  - libparquet=20.0.0
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsentencepiece=0.2.0
  - libsqlite=3.49.2
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libthrift=0.21.0
  - libutf8proc=2.10.0
  - libuuid=2.38.1
  - libuv=1.50.0
  - libxcrypt=4.4.36
  - libxml2=2.13.8
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - markupsafe=3.0.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.4.3
  - multiprocess=0.70.17
  - ncurses=6.5
  - networkx=3.4.2
  - nlohmann_json=3.12.0
  - nomkl=1.0
  - numexpr=2.10.2
  - numpy=1.26.4
  - openblas=0.3.29
  - openssl=3.5.0
  - orc=2.1.2
  - packaging=25.0
  - pandas=2.2.3
  - pip=25.1.1
  - prometheus-cpp=1.3.0
  - propcache=0.3.1
  - pyarrow=20.0.0
  - pyarrow-core=20.0.0
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.10.17
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - python_abi=3.10
  - pytz=2025.2
  - pyyaml=6.0.2
  - re2=2024.07.02
  - readline=8.2
  - regex=2024.11.6
  - requests=2.32.3
  - responses=0.25.7
  - s2n=1.5.18
  - safetensors=0.5.3
  - sentencepiece=0.2.0
  - sentencepiece-python=0.2.0
  - sentencepiece-spm=0.2.0
  - six=1.17.0
  - sleef=3.8
  - snappy=1.2.1
  - sqlite=3.49.2
  - tk=8.6.13
  - tokenizers=0.21.1
  - tqdm=4.67.1
  - transformers=4.51.3
  - types-pyyaml=6.0.12.20250402
  - typing-extensions=4.13.2
  - typing_extensions=4.13.2
  - tzdata=2025b
  - urllib3=2.4.0
  - wheel=0.45.1
  - xxhash=0.8.3
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yarl=1.20.0
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - accelerate==1.6.0
      - airportsdata==20250224
      - annotated-types==0.7.0
      - anyio==4.9.0
      - astor==0.8.1
      - blake3==1.0.4
      - cachetools==5.5.2
      - click==8.2.0
      - cloudpickle==3.1.1
      - cupy-cuda12x==13.4.1
      - deprecated==1.2.18
      - depyf==0.18.0
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.7.0
      - einops==0.8.1
      - email-validator==2.2.0
      - exceptiongroup==1.3.0
      - fastrlock==0.8.3
      - flatbuffers==25.2.10
      - gguf==0.16.3
      - googleapis-common-protos==1.70.0
      - grpcio==1.71.0
      - h11==0.16.0
      - hf-xet==1.1.0
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.31.1
      - importlib-metadata==8.0.0
      - interegular==0.3.3
      - jiter==0.9.0
      - jsonschema-specifications==2025.4.1
      - lark==1.2.2
      - llguidance==0.7.19
      - llvmlite==0.44.0
      - lm-format-enforcer==0.10.11
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - msgpack==1.1.0
      - msgspec==0.19.0
      - nest-asyncio==1.6.0
      - ninja==1.11.1.4
      - numba==0.61.2
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - onnx==1.17.0
      - onnxruntime==1.15.1
      - onnxruntime-extensions==0.14.0
      - opencv-python-headless==4.11.0.86
      - opentelemetry-api==1.26.0
      - opentelemetry-exporter-otlp-proto-common==1.26.0
      - opentelemetry-proto==1.26.0
      - opentelemetry-semantic-conventions-ai==0.4.8
      - optimum==1.24.0
      - optimum-amd==0.1.0
      - partial-json-parser==0.2.1.1.post5
      - pillow==11.2.1
      - prometheus-client==0.21.1
      - protobuf==4.25.7
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pycountry==24.6.1
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pygments==2.19.1
      - python-dotenv==1.1.0
      - python-json-logger==3.3.0
      - python-multipart==0.0.20
      - pytorch-triton-rocm==3.0.0+rocm6.3.4.git75cc27c2
      - pyzmq==26.4.0
      - referencing==0.36.2
      - rich==14.0.0
      - rpds-py==0.24.0
      - scipy==1.15.3
      - setuptools==80.3.1
      - shellingham==1.5.4
      - sniffio==1.3.1
      - starlette==0.46.2
      - sympy==1.13.1
      - tiktoken==0.9.0
      - torch==2.4.0+rocm6.3.4.git7cecbf6d
      - torchaudio==2.4.0+rocm6.3.4.git69d40773
      - torchvision==0.19.0+rocm6.3.4.gitfab84886
      - triton==3.2.0
      - typer==0.15.3
      - typing-inspection==0.4.0
      - uvicorn==0.34.2
      - uvloop==0.21.0
      - watchfiles==1.0.5
      - websockets==15.0.1
      - wrapt==1.17.2
prefix: /home/jade/anaconda3/envs/rocm310
